/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.time.Duration;
import java.time.LocalDateTime;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import io.github.bonigarcia.wdm.WebDriverManager;

public class Qsanity {
    private static WebDriver driver;

    public static WebDriver Create_Driver(String browser) {
        switch (browser.toLowerCase()) {
            case "chrome":
                WebDriverManager.chromedriver().setup();
                driver = new ChromeDriver();
                break;
            case "firefox":
                WebDriverManager.firefoxdriver().setup();
                driver = new FirefoxDriver();
                break;
            default:
                throw new IllegalArgumentException("Invalid browser name: " + browser);
        }
        return driver;
    }

    public static void logstatus(String Type, String Message, String Status) {
        System.out.println(String.format("%s | %s | %s | %s", LocalDateTime.now(), Type, Message, Status));
    }

    public static void Take_Screenshot(WebDriver driver, String Screenshortype, String Description) {
        try {
            File thedir = new File("Screenshorts");
            if (!thedir.exists()) {
                thedir.mkdir();
            }
            String timestamp = LocalDateTime.now().toString().replace(" ", "_").replace(":", "-");
            String filename = String.format("Screenshort_%s_%s_%s.png", timestamp, Screenshortype, Description);
            TakesScreenshot scrshot = (TakesScreenshot) driver;
            File srcfile = scrshot.getScreenshotAs(OutputType.FILE);
            File destfile = new File(thedir, filename);
            FileUtils.copyFile(srcfile, destfile);
        } catch (Exception e) {
            System.out.println("Exception occurred");
        }
    }

    public static boolean Testcase_001() {
        boolean status;
        logstatus("StartTestCase", "Verify Login page", "Done");
        LoginPage  loginpage = new LoginPage(driver);
        loginpage.LoginPage_Navigation();
        status = driver.getCurrentUrl().equals(loginpage.url);
        if (!status) {
            Take_Screenshot(driver, "Testcase_001", "LoginPage_Navigation");
            logstatus("Testcase_001", "Verify User able to navigate to login page", "Failed");
            logstatus("EndTestCase", "Verify Login page", status ? "PASS" : "FAIL");
            return false;
        } else {
            Take_Screenshot(driver, "Testcase_001", "LoginPage_Navigation");
            logstatus("EndTestCase", "Verify Login page", "PASS");
            return true;
        }
    }

    public static void main(String[] args) {
        int TotalTestCases = 0;
        int PassedTestCases = 0;
        boolean status;
        driver = Create_Driver("chrome");
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
        try {
            TotalTestCases += 1;
            status = Testcase_001();
            if (status) {
                PassedTestCases += 1;
            }
            System.out.println("");
        } catch (Exception e) {
            System.out.println("Exception occured while executing the test cases");
        } finally {
            driver.quit();
        }
        System.out.println(String.format("%s out of %s test cases passed", Integer.toString(PassedTestCases), Integer.toString(TotalTestCases)));
    }
}

