/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class QsanityTest {
    @Test public void appHasAGreeting() {
        Qsanity classUnderTest = new Qsanity();
        
    }
}
